import AutoUuid from './components/fieldtypes/AutoUuid.vue';
import LibraryScan from './components/fieldtypes/LibraryScan.vue';
import './components/fieldtypes/ResponsiveFieldtype.js';
import './components/fieldtypes/ColumnSpanFieldtype.js';
import './components/fieldtypes/IconButtonGroupFieldtype.js';
import './components/fieldtypes/UniqueSetsFieldtype.js';
import './components/fieldtypes/GlobalsPickerFieldtype.js';
import './components/fieldtypes/ToolbarAccessFieldtype.js';
import './components/fieldtypes/DefaultSetsFieldtype.js';
import './components/fieldtypes/BardDefaultFieldtype.js';
import './components/LockedRows.js';
import './sibling-sync.js';
import './components/UniqueSets.js';
import './components/SectionAccordion.js';
import './inline-edit.js';
import './section-library.js';
import './lp-panel.js';
import './page-activity.js';
import './outline-panel.js';
import './block-tree.js';
import './focus-panel.js';
import './open-in-preview.js';
import './globals-panel.js';
import './pages.js';
import './global-section.js';
import './chrome.js';
import { initCp } from './cp.js';
import { initComments } from './comments.js';

Statamic.booting(() => {
  Statamic.component('auto_uuid-fieldtype', AutoUuid);
  Statamic.component('library_scan-fieldtype', LibraryScan);
  initCp();
  initComments();
});
