/** Shared Live Preview UI state. This file imports nothing from cp.js. */
export const sveState = {
  lpCollapsed: null,
  forcePanelOpen: false,
  headerTab: undefined,
  listViewTab: 'tree',
  soloUid: null,
  soloAncestors: null,
  chromeValuesBaseline: null,
  lpEnterSidebarClosed: null,
  dockedHeaderRestored: false,
  sectionValuesBaseline: null,
  sectionValuesMatchBaseline: true,
  pendingEditUntilPanel: null,
  lpWidthDragging: false,
  soloObserver: null,
  foldedFor: null,
  dockRestorePaused: false,
  /** True once the preview has painted and remembered chrome may prefetch. */
  lpReady: false,
  globalsStashActive: false,
  chromePrefetchArmed: false,
  /** Section-template prefetch for the HTML tree: queued at overlay boot, run once the preview has painted. */
  htmlTreePrefetchScheduled: false,
  htmlTreePrefetchArmed: false,
  sectionPanelValues: null,
  sectionBaselineUntil: 0,
  libraryDrag: null,
  lpHeaderBgCache: null,
  lpCloseHideObserver: null,
  pendingFocusUntilPanel: null,
  chromeValuesSeen: null,
};
