import { reactive } from 'vue';

export const htmlTreeUi = reactive({
  emptyText: '',
  rows: [],
  // The page's own sections, above the tags. One row each, and the section whose
  // file the dock is showing is the only one holding its tags — see html-tree.js.
  sections: [],
  // Publish form has page_sections (even when the list is empty). The plus stays.
  pageBuilder: false,
  onSection: null,
  // Read the page again now, rather than waiting for the dock to announce a new
  // file. A section added from inside the panel changes the form's values and
  // nothing else — there is no `dock:html-changed` behind it.
  onRefresh: null,
  editingId: null,
  draft: '',
  renameTitle: '',
  hideTitle: '',
  showTitle: '',
  duplicateTitle: '',
  deleteTitle: '',
  lockedTitle: '',
  canEdit: false,
  dragging: false,
  dropId: null,
  dropPlace: null,
  onSelect: null,
  onTwist: null,
  tagTitle: '',
  onTagChange: null,
  onRename: null,
  onRenameCommit: null,
  onRenameCancel: null,
  onHide: null,
  onDuplicate: null,
  onDelete: null,
  onPointerDown: null,
  onContext: null,
  slotText: '',
  dataTitle: '',
  pageTitle: '',
  onInspectData: null,
  onPropValue: null,
  onPropPage: null,
  onPropHost: null,
  onLoopSortField: null,
  onLoopSortDir: null,
  onLoopLimit: null,
  inspect: null,
  onInspectCommit: null,
  onLoopKind: null,
  onAddBranch: null,
  // The way out of a component. Off for a section: there is nothing to leave.
  exitOpen: false,
  exitName: '',
  exitLabel: '',
  exitTitle: '',
  onExit: null,
});
